spring:
  #  mvc:
  #    static-path-pattern: /res/**          #设置静态资源访问前缀

  datasource:
    url: jdbc:mysql:///personnel_management?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis-plus:
    mapper-locations: classpath*:mapper/*.xml


  thymeleaf:
    enabled: false
    check-template: false
server:
  address: 0.0.0.0